### ISSUE TITLE
What is the reason for the mismatch in results?

### ISSUE THREAD

**Issue by lishangli** [yhqiu16/FDRA#7]
This emulator compiled with JTAG Remote Bitbang client. To enable, use +jtag_rbb_enable=1.
Listening on port 42453
[UART] UART0 is here (stdin/stdout).
Initialization finished!
It takes 8295 cycles for CPU to finish the task.
It takes 1717 cycles for CGRA to finish the task(1).
(2, 15, 0): 0, 3433
(2, 15, 3): 0, 4117
(2, 15, 6): 0, 4801
(2, 15, 9): 0, 5485
(2, 15, 12): 0, 6169
(2, 15, 15): 0, 6853
(2, 14, 0): 0, 2799
(2, 14, 3): 0, 3396
(2, 14, 6): 0, 3993
(2, 14, 9): 0, 4590
(2, 14, 12): 0, 5187
(2, 14, 15): 0, 5784
(2, 13, 0): 0, 2249
...

What is the reason for the mismatch in results?

**Comment by yhqiu16** [comment]
I'm wondering whether the cgra_execute() in the software/tests/bareMetalC/xxx.c is consistent with the CGRA configuration. Could you try the conv2d_3x3.c example to check the result?

**Comment by lishangli** [comment]
Thank you very much for your reply. Based on your prompt, I have now resolved the issue.
