### ISSUE TITLE
Error results generated from reading and storing the same address

### ISSUE THREAD

**Issue by lishangli** [yhqiu16/FDRA#8]
When I need to use code like a [i]= a [i] + 1,that is to say, there is a situation where a read operation is performed on an address  and then stored in that address in one iteration. it seems like there are always some errors result. What should I do?
Looking forward to a reply！

**Comment by yhqiu16** [comment]
In this case, the load node and the store node should be bound to the same one during the mapping. We are working on that.
Besides, this kind of computing with a high locality is friendly to the CPU and hard for CGRA to obtain performance benefits.

**Comment by lishangli** [comment]
Thanks!
